---
title: "Basic_stats"
author: "lushi"
date: "26/03/2019"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#This file shows the basic demographic information from the annotated users (N= 77)
```{r cars}
library(tidyverse)
```

Continous variables
```{r pressure, echo=FALSE}
#setwd('/Users/lucia/phd_work/cognitive_distortion/') 
#'/home/lucia/phd_work/mypersonality_data/cognitive_distortion/'
allData <- read.csv('/home/lucia/phd_work/mypersonality_data/cognitive_distortion/data/important_data/user_scale_post_time2.csv')
allData <- subset(allData, age > 17 | is.na(age))
#merge with annotated users
users <- read.csv('/home/lucia/phd_work/mypersonality_data/cognitive_distortion/data/important_data/twoM_newLabels2.csv')
users <- users[!duplicated(users$userid), ]
users <- users$userid
AnnotatedUsersInf <- allData[allData$userid %in% users,]
#select continous values
SelData <- AnnotatedUsersInf[, c(5:6, 14, 24, 26:30, 36:37)]
summary(SelData)

```



```{r }
p1  <- boxplot(SelData[, c(1:2, 4)], data=SelData, main="Demographic Informtation", names=names(SelData[, c(1:2, 4)]))
p2 <- boxplot(SelData[, c(3, 11)], data=SelData, main="Demographic Informtation", names=names(SelData[, c(3, 11)]))
p3 <- boxplot(SelData[, c(5:9)], data=SelData, main="Demographic Informtation", names=names(SelData[, c(5:9)]))
```

Categorical variables
Percentage of people in specific demographic groups
Since the instructions from the website was down, we don't have information for the acronyms 
```{r }
SelDataCat <- AnnotatedUsersInf[, c(9:10, 12, 23)]
prop.table(table(SelDataCat$marital_status))
prop.table(table(SelDataCat$ethnicity))
prop.table(table(SelDataCat$gender))
prop.table(table(SelDataCat$locale))
```

gender female = 1, male = 0
```{r }
#cut off score as 16
table(AnnotatedUsersInf$gender, AnnotatedUsersInf$CESD_sum > 16)
table(AnnotatedUsersInf$gender, AnnotatedUsersInf$CESD_sum > 21)




```



