---
title: "correlationMatrix"
author: "lushi"
date: "13/03/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(Hmisc)
require(psych)
#devtools::install_github("mdscheuerell/muti")
require(muti)
require(gam)
require(jmuOutlier)
require(rlist)
```

## valenceVec frequency with empty days and all variables
```{r read file}
#/Users/lucia/phd_work/cognitive_distortion/
file1 <- read.csv("/home/lucia/phd_work/mypersonality_data/cognitive_distortion/newScripts/moodVector/moodVectorsData/ValenceEmptyFreqAllVar.csv")

getCorrelations <- function(file){
  #get correlations between vars
  file['userid'] <- NULL
  file['X'] <- NULL
  #ValenceEmptyFreqcorMa <- rcorr.adjust(as.matrix(file))
  ValenceEmptyFreqcorMa <- corr.test(as.matrix(file),use = "pairwise", method="pearson",adjust="holm",alpha=.05)
  print(ValenceEmptyFreqcorMa)
}

getPermutation <- function(file, polarity_cols, psy_cols){
  #calculate permutation p
  pvalue_l <- list()
  for (col in names(file[polarity_cols])){
    for (psy in names(file[psy_cols])){
      result <- perm.cor.test(file[[col]], file[[psy]], method='pearson')
      pvalue_l[[paste(col, psy)]] <- result$p.value
  }
} 
return (pvalue_l)
}


getRegression <- function(file, regFile){
  g <- lm(file$agr ~ .,  data=regFile,
  trace=TRUE)
  summary(g)
}

getCorrelations(file1)
permutation_result <- getPermutation(file1, 2:6, 8:14)

regFile = file[2:6]
getRegression(file, regFile)

```

#post valence transition without empty days

```{r pressure, echo=FALSE}

file2 <- read.csv("/home/lucia/phd_work/mypersonality_data/cognitive_distortion/newScripts/moodVector/moodVectorsData/ValenceNoEmptyAllVar.csv")
getCorrelations(file2)
permutation_result2 <- getPermutation(file2, 2:11, 14:20)

```

# mood transitions
```{r }
file3 <- read.csv("/home/lucia/phd_work/mypersonality_data/cognitive_distortion/newScripts/moodVector/moodVectorsData/MoodVecAllVar.csv")
getCorrelations(file3)
permutation_result3 <- getPermutation(file3, 2:16, 19:25)

```

#post valence transition with empty days
```{r }
file4 <- read.csv("/home/lucia/phd_work/mypersonality_data/cognitive_distortion/newScripts/moodVector/moodVectorsData/ValenceEmptyAllVar.csv")
getCorrelations(file4)
permutation_result4 <- getPermutation(file4, 2:16, 19:25)

```

```{r }

file5 <- read.csv("/home/lucia/phd_work/mypersonality_data/cognitive_distortion/newScripts/moodVector/moodVectorsData/PostsLyricsTranEmptyAllVar.csv")
getCorrelations(file5)
permutation_result5 <- getPermutation(file4, 2:8, 11:17)

```


#Use mutual information 
```{r}

muti(file$CESD_sum, file$EmptyAndMix)

```
#Generalized Additive Models
```{r }
g <- gam(agr ~ emptyTran +negaTran + emptyTran+ negaTran+posiTran+mixTran + neuTran+ PosAndNeg+ MixAndPos +MixAndNeg +MixAndNeu +NeuAndPos+ NeuAndNeg + EmptyAndPos+ EmptyAndNeg +EmptyAndMix +EmptyAndNeu, family = gaussian, data=file,
trace=TRUE)
summary(g)


```

```{r }
g <- gam(agr ~ emptyTran +negaTran + emptyTran+ negaTran+posiTran+mixTran + neuTran+ PosAndNeg+ MixAndPos +MixAndNeg +MixAndNeu +NeuAndPos+ NeuAndNeg + EmptyAndPos+ EmptyAndNeg +EmptyAndMix +EmptyAndNeu, family = gaussian, data=file,
trace=TRUE)
summary(g)


```

```{r }
file2 <- file2[, c(2:11,13)]
file3 <- file3[, c(2:16,18)]
file4 <- file4[, c(2:16,18)]
allFile <- merge(file1, file2, by = 'userid')
allFile <- merge(allFile, file3, by = 'userid')
allFile <- merge(allFile, file4, by = 'userid')

fea <- allFile[, c(3:7, 15:54)]
reg <- lm(allFile$neu ~., data = fea)
summary(reg)
```



